import{_ as t}from"./TODO.26b168f1.js";import{_ as l}from"./app.449ba84e.js";import{h as e,o as n,a as o,w as a,b as i,k as p}from"./vendor.80607e96.js";const r=i("li",null,[i("p",null,"适应新版本的图表内容绘制"),i("ul",null,[i("li",null,"18:12 基本上能够比较流畅的运行了，不过由于测试数据过于少，稳定性还需要再多调试调试")])],-1),u=i("li",null,[i("p",null,"竞赛系统问题解决"),i("ul",null,[i("li",null,"15:25 解决了后台测试时，python 脚本跑飞之后无法正确捕捉到错误，并更新测试状态的 bug。 顺便也把 shell 脚本里面 exit code 相关的内容过了一下。可以尝试写点笔记啥的")])],-1),s=p(" 修改 HIAI 抓模型是否是否用 aipp 以及 modelfmt 和 inputfmt 的格式。"),c=i("ul",null,[i("li",null,"18:15 中间花了些时间定位 Pascal vega 测试问题，主要是有一些新的 eval 类型没有同步到 vega 那边。所以导致了一些 eval 的错误。耽误了这个任务的进行。这是一个同步问题，算法那边更新了这个格式的处理，而 vega 那边没有感知，所以导致了一些偏差。")],-1),m={expose:[],setup(p){const m={title:"GTD-21M12",date:"2020-06-24T00:00:00.000Z",author:"Linkang Chan",twitter:"JessEisen_LJ",description:"GTD",public:!0,tag:"21M11 2020-06-24",meta:[{property:"og:title",content:"GTD-21M12"},{property:"og:description",content:"GTD"},{name:"description",content:"GTD"}]};return e({title:"GTD-21M12",meta:[{property:"og:title",content:"GTD-21M12"},{property:"og:description",content:"GTD"},{name:"description",content:"GTD"}]}),(e,p)=>{const d=t,T=l;return n(),o(T,{frontmatter:m},{default:a((()=>[i("div",null,[i("ul",null,[r,u,i("li",null,[i("p",null,[i(d),s]),c])])])])),_:1})}}};export default m;
